version: '3.3'

services:
  redis:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'
    image: redis:7.2
    restart: on-failure
    expose:
      - 6379
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes --requirepass e64a1e3065c49e781aa2721ce86e2725
  main-service:
    build:
      context: main-service
      dockerfile: Dockerfile.main-service
    ports:
      - 7777:7777
    command: go run . -private signature.pem -public signature.pub
  redis-tasks:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'
    image: redis:7.2
    restart: on-failure
    expose:
      - 6380
    volumes:
      - "./task-data:/data"
    command: redis-server --appendonly yes --requirepass e64a1e3065c49e781aa2721ce86e2725 --port 6380
  task-service:
    build:
      context: task-service
      dockerfile: Dockerfile.task-service
    expose:
      - 50051
    command: python3 main.py

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    expose:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    expose:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_DEFAULT_DATABASE=default
    volumes:
      - ./stat-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  stat-service:
    build:
      context: stat-service
      dockerfile: Dockerfile.stat-service
    expose:
      - 50051
    command: python3 main.py