# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\"A\n\rCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\t\"!\n\x0e\x43reateResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"b\n\rUpdateRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"\x10\n\x0eUpdateResponse\"2\n\rDeleteRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\"\x10\n\x0e\x44\x65leteResponse\"\x1d\n\nGetRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"O\n\x0bGetResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08owner_id\x18\x04 \x01(\t\"C\n\x0eGetListRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rom_pos\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\'\n\x0fGetListResponse\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"G\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t2\xe8\x01\n\x0bTaskService\x12+\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x12+\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x12\"\n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\"\x00\x12.\n\x07GetList\x12\x0f.GetListRequest\x1a\x10.GetListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATEREQUEST']._serialized_start=22
  _globals['_CREATEREQUEST']._serialized_end=87
  _globals['_CREATERESPONSE']._serialized_start=89
  _globals['_CREATERESPONSE']._serialized_end=122
  _globals['_UPDATEREQUEST']._serialized_start=124
  _globals['_UPDATEREQUEST']._serialized_end=222
  _globals['_UPDATERESPONSE']._serialized_start=224
  _globals['_UPDATERESPONSE']._serialized_end=240
  _globals['_DELETEREQUEST']._serialized_start=242
  _globals['_DELETEREQUEST']._serialized_end=292
  _globals['_DELETERESPONSE']._serialized_start=294
  _globals['_DELETERESPONSE']._serialized_end=310
  _globals['_GETREQUEST']._serialized_start=312
  _globals['_GETREQUEST']._serialized_end=341
  _globals['_GETRESPONSE']._serialized_start=343
  _globals['_GETRESPONSE']._serialized_end=422
  _globals['_GETLISTREQUEST']._serialized_start=424
  _globals['_GETLISTREQUEST']._serialized_end=491
  _globals['_GETLISTRESPONSE']._serialized_start=493
  _globals['_GETLISTRESPONSE']._serialized_end=532
  _globals['_TASK']._serialized_start=534
  _globals['_TASK']._serialized_end=605
  _globals['_TASKSERVICE']._serialized_start=608
  _globals['_TASKSERVICE']._serialized_end=840
# @@protoc_insertion_point(module_scope)
