version: '3.3'

services:
  redis:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'
    image: redis:7.2
    restart: on-failure
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes --requirepass e64a1e3065c49e781aa2721ce86e2725
  main-service:
    build:
      context: .
      dockerfile: Dockerfile.main-service
    ports:
      - 7777:7777
    command: go run . -private signature.pem -public signature.pub