# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12stat-service.proto\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x17GetViewsAndLikesRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"I\n\x18GetViewsAndLikesResponse\x12\r\n\x05views\x18\x01 \x01(\x05\x12\r\n\x05likes\x18\x02 \x01(\x05\x12\x0f\n\x07task_id\x18\x03 \x01(\t\"1\n GetTop5LikedOrViewedTasksRequest\x12\r\n\x05likes\x18\x01 \x01(\x08\"\x97\x01\n!GetTop5LikedOrViewedTasksResponse\x12@\n\x05tasks\x18\x01 \x03(\x0b\x32\x31.GetTop5LikedOrViewedTasksResponse.TaskIdAndCount\x1a\x30\n\x0eTaskIdAndCount\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x97\x01\n\x19GetTop3LikedUsersResponse\x12?\n\x08user_ids\x18\x01 \x03(\x0b\x32-.GetTop3LikedUsersResponse.UserIdAndLikeCount\x1a\x39\n\x12UserIdAndLikeCount\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nlike_count\x18\x02 \x01(\x05\x32\x89\x02\n\x0bStatService\x12I\n\x10GetViewsAndLikes\x12\x18.GetViewsAndLikesRequest\x1a\x19.GetViewsAndLikesResponse\"\x00\x12\x64\n\x19GetTop5LikedOrViewedTasks\x12!.GetTop5LikedOrViewedTasksRequest\x1a\".GetTop5LikedOrViewedTasksResponse\"\x00\x12I\n\x11GetTop3LikedUsers\x12\x16.google.protobuf.Empty\x1a\x1a.GetTop3LikedUsersResponse\"\x00\x42+Z)github.com/user/task-tracker/stat_serviceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stat_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/user/task-tracker/stat_service'
  _GETVIEWSANDLIKESREQUEST._serialized_start=51
  _GETVIEWSANDLIKESREQUEST._serialized_end=93
  _GETVIEWSANDLIKESRESPONSE._serialized_start=95
  _GETVIEWSANDLIKESRESPONSE._serialized_end=168
  _GETTOP5LIKEDORVIEWEDTASKSREQUEST._serialized_start=170
  _GETTOP5LIKEDORVIEWEDTASKSREQUEST._serialized_end=219
  _GETTOP5LIKEDORVIEWEDTASKSRESPONSE._serialized_start=222
  _GETTOP5LIKEDORVIEWEDTASKSRESPONSE._serialized_end=373
  _GETTOP5LIKEDORVIEWEDTASKSRESPONSE_TASKIDANDCOUNT._serialized_start=325
  _GETTOP5LIKEDORVIEWEDTASKSRESPONSE_TASKIDANDCOUNT._serialized_end=373
  _GETTOP3LIKEDUSERSRESPONSE._serialized_start=376
  _GETTOP3LIKEDUSERSRESPONSE._serialized_end=527
  _GETTOP3LIKEDUSERSRESPONSE_USERIDANDLIKECOUNT._serialized_start=470
  _GETTOP3LIKEDUSERSRESPONSE_USERIDANDLIKECOUNT._serialized_end=527
  _STATSERVICE._serialized_start=530
  _STATSERVICE._serialized_end=795
# @@protoc_insertion_point(module_scope)
